name: Reusable workflow for jslint

on:
  workflow_call:
    inputs:
      workflow_id:
         required: true
         type: string
         description: "ID or filename of the workflow to get latest successful commit"
      files_to_match:
         description: "Check for changes using only this list of files or regex (Defaults to the entire repo)"
         required: true
         type: string
         default: (^|\/)yarn\.lock$
      frontend_config_file:
         required: true
         type: string
         description: "ID or filename of the workflow to get latest successful commit"
      backend_config_file:
         required: false
         type: string
         description: "ID or filename of the workflow to get latest successful commit"
      frontend_wd: 
         required: true
         type: string
         description: "A working directory passed from the caller workflow"
      backend_wd: 
         required: false
         type: string
         description: "A working directory passed from the caller workflow"
       
    secrets:
      gh_token:
         required:  true
      gh_repo_read_token:
         required:  true
jobs:
  changed_tf_files_job:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.changed_files }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      # HACK: ideally this should be moved inside `github-actions/terraform-fmt`
      # but then post checkout action fails with no obvious way to fix it
      - uses: actions/checkout@v2
        with:
          # NOTE: we need to fetch commits for `push` trigger
          # as tj-actions/changed-files@v12 used by `test/javascript-lint` requires this
          fetch-depth: 0

      - name: Checkout actions repo
        uses: actions/checkout@v2
        with:
          repository: saiteja-organization/test1
          path: test1
          ref: main
          token: ${{ secrets.gh_token }}

      - name: Get changed tf files
        id: changed-files
        uses: ./test1/.github/actions/changed-files-since-last-success
        with:
          files_to_match: ${{ inputs.files_to_match }}
          github_token: ${{ secrets.gh_token }}
          workflow_id: ${{ inputs.workflow_id }}
          
  audit_ci_frontend_job:
    runs-on: ubuntu-latest
    needs: changed_tf_files_job
    if: needs.changed_tf_files_job.outputs.any_changed == 'true'
    steps:
      - uses: actions/checkout@v2
        
      - name: Checkout actions repo
        uses: actions/checkout@v2
        with:
          repository: saiteja-organization/test1
          path: test1
          ref: main
          token: ${{ secrets.gh_token }}       

      - name: Get changed tf file for frontend
        if: always()
        id: check-javascript-lint1
        uses: ./test1/.github/actions/javascript-lint
        with:
          frontend_config_file: ${{ inputs.frontend_config_file }}
          frontend_wd: ${{ inputs.frontend_wd }}
        
        

          
      - name: Get changed tf file for frontend
        if: always()
        id: check-javascript-lint2
        uses: ./test1/.github/actions/javascript-lint
        with:
          backend_config_file:  ${{ inputs.backend_config_file }}
          backend_wd: ${{ inputs.backend_wd }}
